app:
  port: 8194
  debug: True
  key: ally-sandbox
max_workers: 4
max_requests: 50
worker_timeout: 5
python_path: /usr/local/bin/python3
enable_network: True # please make sure there is no network risk in your environment
proxy:
  socks5: ''
  http: ''
  https: ''
